In [ ]:
Day 7

In [1]:
import pandas as pd

In [10]:
df=pd.DataFrame({
    "Name":["Khush","Jigyasa","Chandrika","Dashika","Paras","Himanshu","Nitesh","Manish","Palak","Bhavya"],
    "CGPA":[9.1,8.4,9,9.2,8.2,8.6,9.1,8.3,8.1,8.3],
    "Grade":["A+","A","A","A+","A","A","A+","A","A","A"]
})

In [11]:
df

        Name  CGPA Grade
0      Khush   9.1    A+
1    Jigyasa   8.4     A
2  Chandrika   9.0     A
3    Dashika   9.2    A+
4      Paras   8.2     A
5   Himanshu   8.6     A
6     Nitesh   9.1    A+
7     Manish   8.3     A
8      Palak   8.1     A
9     Bhavya   8.3     A

In [12]:
df.tail()

       Name  CGPA Grade
5  Himanshu   8.6     A
6    Nitesh   9.1    A+
7    Manish   8.3     A
8     Palak   8.1     A
9    Bhavya   8.3     A

In [13]:
df.head()

        Name  CGPA Grade
0      Khush   9.1    A+
1    Jigyasa   8.4     A
2  Chandrika   9.0     A
3    Dashika   9.2    A+
4      Paras   8.2     A

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   CGPA    10 non-null     float64
 2   Grade   10 non-null     object
dtypes: float64(1), object(2)
memory usage: 372.0+ bytes

In [16]:
df.describe()

            CGPA
count  10.000000
mean    8.630000
std     0.427005
min     8.100000
25%     8.300000
50%     8.500000
75%     9.075000
max     9.200000

In [17]:
#for understanding mean
1,2,1,3,1,3,1,100,12300

(1, 2, 1, 3, 1, 3, 1, 100, 12300)

In [21]:
average=(1+2+1+3+1+3+1+100+12300)/9  #12300 is outlier(number in dataset that is much larger or smaller than all other numbers)

In [22]:
average

1379.111111111111

In [23]:
df.isnull()

    Name   CGPA  Grade
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [24]:
df.isnull().sum()

Name     0
CGPA     0
Grade    0
dtype: int64

In [ ]:
there is three types of data:
1)numerical
2)categorical
3)ordinal

In [ ]:
filling-:
1.Mode- categorical, ordinal
2.Median- outliers
3.Mean- no outliers

In [ ]:
df.fillna()

In [31]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.drop_duplicates()  #to drop duplicates

        Name  CGPA Grade
0      Khush   9.1    A+
1    Jigyasa   8.4     A
2  Chandrika   9.0     A
3    Dashika   9.2    A+
4      Paras   8.2     A
5   Himanshu   8.6     A
6     Nitesh   9.1    A+
7     Manish   8.3     A
8      Palak   8.1     A
9     Bhavya   8.3     A

In [87]:
df.drop_duplicates().reset_index(drop="TRUE")

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
1787,43.0,Female,Master's Degree,Digital Marketing Manager,15.0,150000.0
1788,27.0,Male,High School,Sales Manager,2.0,40000.0
1789,33.0,Female,Bachelor's Degree,Director of Marketing,8.0,80000.0
1790,37.0,Male,Bachelor's Degree,Sales Director,7.0,90000.0
1791,30.0,Female,Bachelor's Degree,Sales Manager,5.0,70000.0

In [34]:
df.dropna()

        Name  CGPA Grade
0      Khush   9.1    A+
1    Jigyasa   8.4     A
2  Chandrika   9.0     A
3    Dashika   9.2    A+
4      Paras   8.2     A
5   Himanshu   8.6     A
6     Nitesh   9.1    A+
7     Manish   8.3     A
8      Palak   8.1     A
9     Bhavya   8.3     A

In [36]:
df.to_excel("khushexcel.xlsx") #to save current file into excel file

In [37]:
import pandas as pd

In [38]:
df=pd.read_csv("salary_data.csv")   #to upload data

In [39]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [ ]:
uploading & Dowanloading
-csv
-excel
-html
-sql
json

In [40]:
df1=df["Salary"]

In [41]:
df1

0        90000.0
1        65000.0
2       150000.0
3        60000.0
4       200000.0
          ...
6699    200000.0
6700     50000.0
6701     55000.0
6702    140000.0
6703     35000.0
Name: Salary, Length: 6704, dtype: float64

In [46]:
df2=df["Salary"][df["Salary"]>100000]  #yeh kam kr raha ha salary>100000

In [47]:
df2

2       150000.0
4       200000.0
6       120000.0
9       110000.0
11      140000.0
          ...
6690    130000.0
6693    140000.0
6697    190000.0
6699    200000.0
6702    140000.0
Name: Salary, Length: 3772, dtype: float64

In [49]:
df1[df1>100000]  #yeh bhi whi kam kr raha jo upar wala kr raha ha salary>100000

2       150000.0
4       200000.0
6       120000.0
9       110000.0
11      140000.0
          ...
6690    130000.0
6693    140000.0
6697    190000.0
6699    200000.0
6702    140000.0
Name: Salary, Length: 3772, dtype: float64

In [50]:
df1[df1>1000000]   #yeh kam kr raha ha salary>1000000

Series([], Name: Salary, dtype: float64)

In [51]:
df1[df1>200000]  #yeh kam kr raha ha salary>200000

30      250000.0
83      250000.0
105     220000.0
1531    210000.0
1655    210000.0
          ...
6200    215000.0
6214    215000.0
6228    215000.0
6242    215000.0
6256    215000.0
Name: Salary, Length: 114, dtype: float64

In [52]:
df["Salary"].max()

250000.0

In [56]:
df[df["Salary"]==250000]  #jinki salary 250000 ha

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
30,50.0,Male,Bachelor's,CEO,25.0,250000.0
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0
5001,45.0,Male,Bachelor's Degree,Financial Manager,21.0,250000.0

In [58]:
df["Education Level"][df["Salary"]==250000]

30             Bachelor's
83                    PhD
5001    Bachelor's Degree
Name: Education Level, dtype: object

In [59]:
df["Salary"].min()

350.0

In [61]:
df[(df["Salary"]>=350)&(df["Salary"]<=50000)]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
14,27.0,Male,Bachelor's,Customer Service Rep,2.0,40000.0
18,25.0,Female,Bachelor's,Data Entry Clerk,0.0,35000.0
22,30.0,Male,Bachelor's,IT Support,2.0,50000.0
25,28.0,Female,Bachelor's,Social Media Specialist,3.0,45000.0
...,...,...,...,...,...,...
6689,26.0,Female,High School,Sales Associate,1.0,35000.0
6692,24.0,Male,Bachelor's Degree,Sales Executive,1.0,35000.0
6694,27.0,Male,High School,Digital Marketing Manager,2.0,40000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [68]:
df[(df["Salary"]>=100000)&(df["Gender"]=="Female")]  #kitni females ki salary 100000 se zada ha

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
6,42.0,Female,Master's,Product Manager,12.0,120000.0
11,48.0,Female,Bachelor's,HR Manager,18.0,140000.0
13,40.0,Female,Master's,Project Manager,14.0,130000.0
26,37.0,Female,Master's,Software Manager,11.0,110000.0
28,43.0,Female,PhD,Senior Consultant,15.0,140000.0
...,...,...,...,...,...,...
6683,51.0,Female,Master's Degree,Content Marketing Manager,19.0,190000.0
6685,49.0,Female,PhD,Senior Product Marketing Manager,20.0,200000.0
6693,43.0,Female,Master's Degree,Sales Manager,14.0,140000.0
6697,51.0,Female,Master's Degree,Senior Product Marketing Manager,19.0,190000.0
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0

In [69]:
df[(df["Salary"]>=100000)&(df["Gender"]=="Male")]  #kitne males ki salary 100000 se zada ha

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
4,52.0,Male,Master's,Director,20.0,200000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0
15,44.0,Male,Bachelor's,Operations Manager,16.0,125000.0
17,39.0,Male,PhD,Senior Engineer,12.0,115000.0
...,...,...,...,...,...,...
6674,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6676,42.0,Male,Bachelor's Degree,Content Marketing Manager,13.0,130000.0
6688,46.0,Male,Master's Degree,Director of Marketing,16.0,160000.0
6690,42.0,Male,Bachelor's Degree,Financial Manager,13.0,130000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0

In [72]:
df[df["Salary"]>=100000]["Gender"].value_counts()  ##kitne males aur females ki salary 100000 se zada ha

Gender
Male      2280
Female    1662
Other       10
Name: count, dtype: int64

In [71]:
df["Gender"].value_counts()  #kitne males females ya others ha company ma

Gender
Male      3674
Female    3014
Other       14
Name: count, dtype: int64

In [73]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [75]:
df[df["Age"]>25]["Gender"].value_counts() #kitne males aur females 25 se upar kam krte ha

Gender
Male      3407
Female    2624
Other       10
Name: count, dtype: int64

In [77]:
df[df["Age"]>50]["Gender"].value_counts() #kitne males aur females 50 se upar kam krte ha

Gender
Male      134
Female     49
Other       6
Name: count, dtype: int64

In [80]:
df[df["Education Level"]=="PhD"]["Gender"].value_counts()  #kitne males aur females ne phd kri hui ha

Gender
Male      872
Female    496
Name: count, dtype: int64

In [81]:
df["Years of Experience"].max()

34.0

In [85]:
df[df["Years of Experience"]==34]["Gender"].value_counts() #kitne male ya female ka years of experience 34 ha

Gender
Female    2
Name: count, dtype: int64

In [86]:
df[df["Years of Experience"]>=30]["Gender"].value_counts() #kitne male ya female ka years of experience 30 ha ya us se upar

Gender
Female    21
Male       6
Other      2
Name: count, dtype: int64